import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import { Header } from "./components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <Header />
        <main className="flex flex-1 overflow-scroll relative">{children}</main>
        <Navbar />
      </body>
    </html>
  );
}
